### ISSUE TITLE
Use vector quantitiy instead of vector of quantity

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/orbit#24]
Getting a plain V3 float currently requires fmapping the `quOf`/`#`. There is a bunch of stuff in `Data.Metrology.Vector` for dealing specifically in `Linear` quantities.

And this should make swapping the `V3 a` for some other representation while retaining the units.

I peeked at the `units` changelog and the vector is stuff is there for some time. Perhaps there is a reason for `orbits` to use units element-wise?

**Comment by expipiplus1** [comment]
Hahha, I don't know if I can remember that from so long ago! I think it
might have been that doing it the other way made things more inconvenient
for internal use?

I'll have another look and see if I can trigger my memory, if I do I'll get
back here.

Related: https://github.com/goldfirere/units/issues/55

**Comment by dpwiz** [comment]
I expected that since you can't have different units in different elements it is silly to ask introducing/discarding units element-wise.

But actually, you can: `V3 (1 % [si| m |]) (1 % [si| m |]) (1 % [si| km |])`, boom, plane in meters and altitude in km.

This, however, don't seem to be useful in orbit calculations. But maybe it does... :sweat_smile:
